// website/src/chat/index.tsx
import React from "react"
import className from "classnames"
import { observer } from "mobx-react-lite"
import { useTranslation } from "react-i18next"
import { Button, Form, Input } from "antd"

import { CommentAltLinesSVG, TimesSVG } from "assets/icons"

import { useRoomStore } from "../room/context"
import { ChatMessage, IAttendee } from "models"

import "./chat.scss"

const Chat = observer(() => {
  const { t } = useTranslation()
  const { roomStore } = useRoomStore()

  const [form] = Form.useForm()

  const getMember = (uid: string): IAttendee | undefined => {
    return roomStore.attendees?.find(item => `${item.uid}` === uid)
  }

  const onFinish = async (values: any) => {

    if (values.content === undefined || values.content.trim() === "") {
      form.resetFields()
      return
    }

    const message = new ChatMessage({
      content: values.content as string,
      uid:  `${roomStore.info?.self.uid}`
    })

    roomStore.RTM.sendMessage(message).then(() => {
      form.resetFields()
      roomStore.RTM.chatMessages.push(message)
    })
  }

  return (
    <div id="chat" className={className({open: roomStore.chatPopUp})}>
      <header>
        <CommentAltLinesSVG height="16" />
        <span style={{ marginLeft: 5 }}>{ t("chat") }</span>

        <Button type="link" size="small" onClick={ () => roomStore.chatPopUp = false }>
          <TimesSVG height="20" />
        </Button>
      </header>

      <ul className="message-list">
        {
          roomStore.RTM.chatMessages.map((message, index) =>
          <li key={`${message.timestamp}-${message.uid}-${index}`} className={className({ "self": `${roomStore.info?.self.uid}` === message.uid })}>
            <div className="avatar">
              <img src="" alt="" width="64" height="64" />
            </div>

            <div className="body">
              <h6 className="userinfo">
                <span>{ getMember(message.uid)?.name || message.uid }</span>
              </h6>
              <p>{ message.content }</p>
            </div>
          </li>
          )
        }
      </ul>

      <Form
        form={form}
        name="signin"
        className="intercom"
        onFinish={onFinish}>

        <Form.Item name="content">
          <Input.TextArea
            autoSize={{minRows: 2, maxRows: 4}}
            placeholder={ t("placeholder_send_message") }
            onPressEnter={ () => { form.submit(); return false } }
          />
        </Form.Item>
      </Form>
    </div>
  )
})

export default Chat

// website/src/components/room/Chat.vue
<template>
  <div id="chat" :class="{open: ChatPopUp}">
    <header>
      <Icon type="comment-alt-lines" height="16" />
      <span class="ml-1">{{ $t('chat') }}</span>

      <b-btn class="float-right" variant="link" size="sm" @click="closeChat()">
        <Icon type="times" height="20" />
      </b-btn>
    </header>

    <ul class="message-list" ref="messageList">
      <li :class="{self: message.userId === RTC.userId}" v-for="(message, index) in chatMessages" :key="`${message.timestamp}-${message.userId}-${index}`">
        <div class="avatar">
          <img :src="`${message.user.avatar}`" width="64" height="64" v-if="message.user.avatar">
        </div>

        <div class="body">
          <h6 class="userinfo">
            <span>{{ message.user.name }}</span>
          </h6>
          <p>{{ message.content }}</p>
        </div>
      </li>
    </ul>

    <form class="intercom" @submit.prevent="sendMessage">
      <input type="text" class="form-control" ref="msgContentBox" v-model.trim="msgContent" :placeholder="$t('placeholder_send_message')">
      <b-button-group class="actions">
        <b-btn variant="link" type="submit" :disabled="msgContent === ''">
          <Icon type="paper-plane" height="22" />
        </b-btn>
      </b-button-group>
    </form>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { mapState, mapMutations, mapActions } from 'vuex';
import * as QNRTC from 'pili-rtc-web';
import { CustomMessage } from 'pili-rtc-web';
import { ChatMessage } from '../../types/message';

export default Vue.extend({
  data() {
    return {
      msgContent: "",
      chatMessages: [] as ChatMessage[]
    }
  },

  computed: {
    ...mapState("user", [
      "signedIn",
      "user"
    ]),

    ...mapState("room", [
      "roomInfo",
      "RTC",
      "ChatPopUp",
      "UnreadCount"
    ])
  },

  methods: {
    ...mapMutations("room", [
      "setChatPopUp",
      "setUnreadCount"
    ]),

    closeChat() {
      this.setChatPopUp(false);
    },
    scrollMessageList() {
      if (this.$refs.messageList === undefined) return

      const messageList = this.$refs.messageList as Element;

      setTimeout(() => {
        var scrollHeight = messageList.scrollHeight
        messageList.scrollTop = scrollHeight
      }, 100)
    },

    sendMessage() {
      const message = this.RTC.encodeChatMessage(this.msgContent);
      this.RTC.sendCustomMessage(message.customMessage());
      this.appendMessage(message);
      this.msgContent = "";
    },

    appendMessage(message: ChatMessage){
      this.chatMessages.push(message);
      this.scrollMessageList()
    }
  },

  watch: {
    ChatPopUp: function (isOpen: boolean) {
      if (isOpen) {
        this.setUnreadCount(0)
      }
    }
  },

  created () {
    this.RTC.on('messages-received', (messages: CustomMessage[]) => {
      for (const message of messages) {
        const chatMessage = this.RTC.parseChatMessage(message);
        this.appendMessage(chatMessage);

        if (!this.ChatPopUp) this.setUnreadCount(this.UnreadCount + 1)
      }
    })
  },

  destroyed() {

  }
})
</script>
