// website-v2/src/room/navbar.tsx
import React, { useEffect, useState } from "react"
import { NavLink } from "react-router-dom"
import { observer } from "mobx-react-lite"
import fscreen from "fscreen"
import { useTranslation } from "react-i18next"
import CopyToClipboard from "react-copy-to-clipboard"
import { Layout, Row, Col, Button, Tooltip, Modal, Input, message } from "antd"

import { ReactComponent as LogoSVG } from "assets/icons/Logo.svg"
import { ReactComponent as ChalkboardSVG } from "assets/icons/Chalkboard.svg"
import { ReactComponent as CommentAltLinesSVG } from "assets/icons/CommentAltLines.svg"
import { ReactComponent as CogSVG } from "assets/icons/Cog.svg"
import { ReactComponent as SignOutAltSVG } from "assets/icons/SignOutAlt.svg"
import { ReactComponent as UserPlusSVG } from "assets/icons/UserPlus.svg"
import { ReactComponent as LinkSVG } from "assets/icons/Link.svg"
import { ReactComponent as MicrophoneSlashSVG } from "assets/icons/MicrophoneSlash.svg"
import { ReactComponent as MicrophoneSVG } from "assets/icons/Microphone.svg"
import { ReactComponent as VideoSlashSVG } from "assets/icons/VideoSlash.svg"
import { ReactComponent as VideoSVG } from "assets/icons/Video.svg"
import { ReactComponent as ScreenNormalSVG } from "assets/icons/ScreenNormal.svg"
import { ReactComponent as ScreenFullSVG } from "assets/icons/ScreenFull.svg"

import { useGlobalStore } from "common/contexts/GlobalContext"
import { useRoomStore } from "./context"
import Settings from "./settings"

import "./room.scss"

const Navbar = observer(() => {
  const { t } = useTranslation()
  const { globalStore } = useGlobalStore()
  const { roomStore } = useRoomStore()

  const shareLink = `https://room.cafe/room/${roomStore.info?.uuid}`

  const [invitePeopleModalVisible, setInvitePeopleModalVisible] = useState(false)
  const [settingsModalVisible, setSettingsModalVisible] = useState(false)

  // 全屏事件监听
  useEffect(() => {
    if (fscreen.fullscreenEnabled) {
      fscreen.addEventListener("fullscreenchange", () => { roomStore.isFullscreen = fscreen.fullscreenElement !== null }, false)
    }
  }, [roomStore])

  // 全屏切换
  const switchFullscreen = () => {
    roomStore.isFullscreen ? fscreen.exitFullscreen() : fscreen.requestFullscreen(document.documentElement)
  }

  // 离开房间
  const exit = async () => {
    await roomStore.leave()
    window.location.href = "/"
  }

  return (
    <Layout.Header className="navbar-room">
      <Row>
        <Col flex="auto">
          <NavLink className="brand" to="/">
            <span>ROOM CAFE</span>
            <LogoSVG width={24} height={24} />
            <sup>Beta</sup>
          </NavLink>
          <span className="nav-item">{globalStore.user?.name}</span>
        </Col>

        <Col>
          <ul className="navbar-nav">
            <li className="nav-item">
              <Tooltip placement="bottom" title={ t("invite_people") }>
                <Button type="link" onClick={() => setInvitePeopleModalVisible(true)}>
                  <UserPlusSVG width={22} height={22} />
                </Button>
              </Tooltip>

              <Modal
                title={t("invite_people")}
                visible={invitePeopleModalVisible}
                onCancel={() => setInvitePeopleModalVisible(false)}
                centered={true}
                footer={null}
                bodyStyle={{ textAlign: "right" }}>
                <Input size="large" readOnly={true} value={shareLink} />

                <CopyToClipboard text={shareLink} onCopy={() => message.success(t("copy_link_success"))}>
                  <Button size="large" style={{ marginTop: 5 }}>
                    <LinkSVG width={18} height={18} style={{ verticalAlign: "middle", marginRight: 3 }} />
                    { t("copy_link_to_share") }
                  </Button>
                </CopyToClipboard>
              </Modal>
            </li>

            <li className="nav-item">
              <Tooltip placement="bottom" title={ t("whiteboard") }>
                <Button type="link">
                  <ChalkboardSVG width={22} height={22} />
                </Button>
              </Tooltip>
            </li>

            <li className="nav-item">
              <Tooltip placement="bottom" title={ roomStore.chatPopUp ? t("close_chat") : t("open_chat") }>
                <Button type="link" onClick={ () => roomStore.chatPopUp = !roomStore.chatPopUp }>
                  <CommentAltLinesSVG width={22} height={22} />
                </Button>
              </Tooltip>
            </li>

            <li className="nav-item">
              <Tooltip placement="bottom" title={ roomStore.localUser.audioMuted ? t("microphone_open") : t("microphone_mute") }>
                <Button type="link" onClick={ () => roomStore.setLocalTrackMute("audio", !roomStore.localUser.audioMuted) }>
                  { roomStore.localUser.audioMuted ? <MicrophoneSlashSVG height={22} /> : <MicrophoneSVG height={22} /> }
                </Button>
              </Tooltip>
            </li>

            <li className="nav-item">
              <Tooltip placement="bottom" title={ roomStore.localUser.videoMuted ? t("video_open") : t("video_mute") }>
                <Button type="link" onClick={ () => roomStore.setLocalTrackMute("video", !roomStore.localUser.videoMuted) }>
                  { roomStore.localUser.videoMuted ? <VideoSlashSVG height={22} /> : <VideoSVG height={22} /> }
                </Button>
              </Tooltip>
            </li>

            {
              fscreen.fullscreenEnabled &&
              <li className="nav-item">
                <Tooltip placement="bottom" title={ roomStore.isFullscreen ? t("fullscreen_exit") : t("fullscreen") }>
                  <Button type="link" onClick={ switchFullscreen }>
                    { roomStore.isFullscreen ? <ScreenNormalSVG height={22} /> :  <ScreenFullSVG height={22} /> }
                  </Button>
                </Tooltip>
              </li>
            }

            <li className="nav-item">
              <Tooltip placement="bottom" title={ t("settings") }>
                <Button type="link" onClick={() => setSettingsModalVisible(true) }>
                  <CogSVG width={22} height={22} />
                </Button>
              </Tooltip>
              <Settings visible={ settingsModalVisible } onCancel={() => setSettingsModalVisible(false) } />
            </li>

            <li className="nav-item">
              <Tooltip placement="bottom" title={ t("exit") }>
                <Button type="link" onClick={ exit }>
                  <SignOutAltSVG width={22} height={22} />
                </Button>
                </Tooltip>
            </li>
          </ul>
        </Col>
      </Row>
    </Layout.Header>
  )
})

export default Navbar

// website/src/components/room/Navbar.vue
<template>
  <b-navbar toggleable="md" fixed="top" type="dark" class="navbar-room">
    <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>

    <b-navbar-brand>
      <span>ROOM CAFE</span>
      <img src="@/assets/images/logo.svg" alt="ROOM CAFE" width="24">

      <small class="ml-2" v-if="signedIn">{{ user.name }}</small>
    </b-navbar-brand>

    <b-collapse is-nav id="nav_collapse">
      <b-navbar-nav class="ml-auto">
        <li class="nav-item">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" @click="$refs.InvitePeopleModal.show()" v-b-tooltip.hover :title="$t('invite_people')">
            <Icon type="user-plus" height="22" class="flip-horizontal" />
          </b-btn>

          <b-modal
            id="InvitePeopleModal"
            ref="InvitePeopleModal"
            centered
            hide-footer
            title="Invite People"
            modal-class="modal-invite-people">

            <b-form-input id="InvitePeopleLink" readonly="readonly" v-model="shareLink"></b-form-input>
            <b-btn variant="outline-primary" class="float-right mt-2" id="CopyShareLinkBtn" ref="CopyShareLinkBtn" @click="copyLink" data-clipboard-target="#InvitePeopleLink">
              <Icon type="link" height="22" rotate="45" class="mr-2" />
              {{ $t('copy_link_to_share') }}
            </b-btn>
          </b-modal>
        </li>

        <li class="nav-item">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" @click="switchWhiteBoard" v-b-tooltip.hover :title="$t('whiteboard')">
            <Icon type="chalkboard" height="22" />
          </b-btn>
        </li>

        <li class="nav-item">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" id="chatBtn" @click="switchChat(); $refs.chatTooltip.$emit('close')">
            <Icon type="comment-alt-lines" height="22" />
            <span class="badge" v-if="UnreadCount > 0">{{ UnreadCount }}</span>
          </b-btn>
          <b-tooltip id="chatTooltip" ref="chatTooltip" target="chatBtn" placement="bottom">{{ ChatPopUp ? $t('close_chat') : $t('open_chat') }}</b-tooltip>
        </li>

        <!-- 屏幕共享 -->
        <ShareScreen tag="li" class="nav-item" v-if="$browser.name === 'chrome' || $browser.name === 'firefox'" />

        <!-- 音频开关 -->
        <li class="nav-item">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" class="btn-microphone" v-b-tooltip.hover :title="microphoneMuted ? $t('microphone_open') : $t('microphone_mute')" @click="switchMicrophone">
            <Icon :type="microphoneMuted ? 'microphone-slash' : 'microphone'" height="22" />
          </b-btn>
        </li>

        <!-- 视频开关 -->
        <li class="nav-item">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" class="btn-video" v-b-tooltip.hover :title="videoMuted ? $t('video_open') : $t('video_mute')" @click="switchVideo">
            <Icon :type="videoMuted ? 'video-slash' : 'video'" height="22" />
          </b-btn>
        </li>

        <!-- 全屏 -->
        <li class="nav-item" v-if="fullscreenEnabled">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" v-b-tooltip.hover :title="isFullscreen ? $t('fullscreen_exit') : $t('fullscreen')" @click="switchFullscreen">
            <Icon :type="isFullscreen ? 'screen-normal' : 'screen-full'" height="22" />
          </b-btn>
        </li>

        <!-- 设置 -->
        <li class="nav-item">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" @click="settings" v-b-tooltip.hover :title="$t('settings')">
            <Icon type="cog" height="22" />
          </b-btn>
          <Settings />
        </li>

        <!-- 退出 -->
        <li class="nav-item">
          <b-btn :disabled="RTC.roomState !== 2" size="sm" variant="link" id="exitBtn" @click="exit(); $refs.exitTooltip.$emit('close')">
            <Icon type="sign-out-alt" height="22" />
          </b-btn>
          <b-tooltip id="exitTooltip" ref="exitTooltip" target="exitBtn" placement="bottom">{{ $t('exit') }}</b-tooltip>
        </li>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<script lang="ts">
import Vue from 'vue';
import { mapState, mapMutations, mapActions } from 'vuex';
import fscreen from 'fscreen';
import Clipboard from 'clipboard';
import { openWindow } from '../../utils/window';
import ShareScreen from './ShareScreen.vue';
import Settings from './Settings.vue';

export default Vue.extend({
  components: {
    ShareScreen,
    Settings
  },

  data () {
    return {
      copyBtn: {} as ClipboardJS, //存储初始化复制按钮事件
      shareLink: "",
      fullscreenEnabled: false,
      isFullscreen: false,
      microphoneMuted: false,
      videoMuted: false,
    }
  },

  computed: {
    ...mapState("user", [
      "signedIn",
      "user"
    ]),

    ...mapState("room", [
      "roomInfo",
      "RTC",
      "ChatPopUp",
      "UnreadCount",
      "Whiteboard"
    ])
  },

  methods: {
    ...mapMutations("room", [
      "setStageStreamId",
      "setChatPopUp"
    ]),

    ...mapActions("user", [
      "fetchState"
    ]),

    // 切换白板
    switchWhiteBoard() {
      this.setStageStreamId("");
    },

    // 切换白板
    switchChat() {
      this.setChatPopUp(!this.ChatPopUp);
    },

    copyLink() {
      let clipboard = this.copyBtn as ClipboardJS;

      if (!clipboard) return;

      clipboard.on("success", () => {
        this.$message.success("Link copied to clipboard.");
      });

      clipboard.on("error", () => {
        this.$message.error("Copy failed. Please copy the url in the input box.");
      });
    },

    // 全屏切换
    switchFullscreen() {
      this.isFullscreen ? fscreen.exitFullscreen(): fscreen.requestFullscreen(document.documentElement);
    },

    settings() {
      this.$root.$emit('bv::show::modal', 'RoomSettingsModal');
    },

    switchMicrophone() {
      this.RTC.muteStream("master", "audio", !this.microphoneMuted);
      this.microphoneMuted = !this.microphoneMuted;
    },

    switchVideo() {
      this.RTC.muteStream("master", "video", !this.videoMuted);
      this.videoMuted = !this.videoMuted;
    },

    async exit() {
      // 释放本地采集
      for (const track of this.RTC.publishedTracks) {
        await track.release();
      }
      this.RTC.leaveRoom();
      // this.Whiteboard.disconnect();
    }
  },

  created () {
    const routeData = this.$router.resolve({name: 'room', params: {id: this.$route.params.id} });
    this.shareLink = `https://room.cafe${routeData.href}`

    if (fscreen.fullscreenEnabled) {
      this.fullscreenEnabled = fscreen.fullscreenEnabled;
      fscreen.addEventListener('fullscreenchange', () => { this.isFullscreen = fscreen.fullscreenElement !== null; }, false);
    }
  },

  mounted () {
    this.copyBtn = new Clipboard(this.$refs.CopyShareLinkBtn as Element);
  }
})
</script>
