// website/src/whiteboard/index.tsx
import React, { useState, useEffect, useCallback } from "react"
import { useTranslation } from "react-i18next"

import { UserCursor } from "@netless/cursor-adapter"
import { Room, RoomPhase, WhiteWebSdk, RoomWhiteboard, JoinRoomParams, Color, MemberState, RoomState } from "white-react-sdk"

import { Button, Tooltip, Menu, Popover, Slider, Upload, message, Spin } from "antd"
import { RcFile, UploadChangeParam } from "antd/lib/upload"

import { LoadingOutlined } from "@ant-design/icons"

import { UploaderAPI } from "api/uploader"
import { IUploaderToken } from "models/uploader"
import { colors } from "utils/color"

import { ChalkboardSVG, MousePointerSVG, PencilAltSVG, TextSVG, SquareSVG, CircleSVG, EraserSVG, ImagesSVG } from "assets/icons"

import { IWhiteboard } from "models"

import "white-web-sdk/style/index.css"
import "./whiteboard.scss"

interface Props {
  whiteboard: IWhiteboard
}

interface IWhiteBoardState {
  room?: Room
  phase?: RoomPhase
}

const initWhiteBoardState: IWhiteBoardState = {}
const initMemberState: MemberState = {
  currentApplianceName: "pencil",
  strokeColor: [],
  strokeWidth: 4,
  textSize: 14,
  pencilOptions: {
    disableBezier: false,
    sparseWidth: 5,
    sparseHump: 5
  }
}

export default function WhiteBoard(props: Props) {
  const { t } = useTranslation()

  const [whiteBoardState, setWhiteBoardState] = useState(initWhiteBoardState)
  const [memberState, setMemberState] = useState(initMemberState)
  const [strokeTooltipState, setStrokeTooltipState] = useState([false, false])
  const [uploaderToken, setUploaderToken] = useState("")
  const [uploading, setUploading] = useState(false)

  // 设置教具
  const setAppliance = (appliance: string) => {
    whiteBoardState.room?.setMemberState({ currentApplianceName: appliance })
  }

  // 设置笔触颜色
  const setStrokeColor = (color: Color) => {
    whiteBoardState.room?.setMemberState({ strokeColor: color })
  }

  // 设置笔触宽度
  const setStrokeWidth = (value: number) => {
    whiteBoardState.room?.setMemberState({ strokeWidth: value })
  }

  // 上传前检查
  const uploaderBeforeUpload = (file: RcFile, fileList: RcFile[]): boolean => {
    if (file.size > 1024 * 1024 * 2) {
      message.error(t("uploader.image_size_limit_hint"))
      return false
    }
    return true
  }

  // 上传状态变化处理
  const uploaderStatusOnChange = (info: UploadChangeParam) => {
    if (info.file.status === "uploading") {
      setUploading(true)
    } else {
      setUploading(false)
    }

    if (info.file.status === "done") {
      const uuid = props.whiteboard.whiteboard_id + +new Date()
      whiteBoardState.room?.insertImage({
        uuid,
        centerX: 0,
        centerY: 0,
        width: info.file.response.imageInfo.width,
        height: info.file.response.imageInfo.height
      })

      UploaderAPI.getURL(info.file.response.key).then((resp) => {
        whiteBoardState.room?.completeImageUpload(uuid, resp.data.url)
      })
    } else if (info.file.status === "error") {
      message.error(t("uploader.image_upload_failed"))
    }
  }

  // 初始化白板
  const initWhiteBoard = useCallback(
    () => {
      const whiteWebSdk = new WhiteWebSdk()
      const cursor = new UserCursor()

      const params: JoinRoomParams = {
        uuid: props.whiteboard.whiteboard_id,
        roomToken: props.whiteboard.whiteboard_token,
        cursorAdapter: cursor,
        userPayload: {
          userId: props.whiteboard.user.uid,
          name: props.whiteboard.user.name,
          avatar: props.whiteboard.user.avatar,
        }
      }

      const callbacks = {
        onRoomStateChanged: (modifyState: Partial<RoomState>) => {
          if (modifyState.memberState) { setMemberState(modifyState.memberState) }
          if (modifyState.roomMembers) { cursor.setColorAndAppliance(modifyState.roomMembers) }
        }
      }

      whiteWebSdk.joinRoom({ ...params, cursorAdapter: cursor }, callbacks)
      .then((room) => {
        cursor.setColorAndAppliance(room.state.roomMembers)
        setWhiteBoardState({ room, phase: RoomPhase.Connected})
        setMemberState(room.state.memberState)
      })
    },
    [props]
  )

  useEffect(() => {
    initWhiteBoard()
  }, [initWhiteBoard])

  useEffect(() => {
    return function cleanup() {
      whiteBoardState.room?.disconnect()
    }
  }, [whiteBoardState])

  // 刷新白板实图大小
  useEffect(() => {
    const refreshRoomViewSize = () => whiteBoardState.room?.refreshViewSize()

    if (whiteBoardState.room !== undefined) {
      window.addEventListener("resize", refreshRoomViewSize)
    }

    return function cleanup() {
      window.removeEventListener("resize", refreshRoomViewSize)
    }
  }, [whiteBoardState.room])

  // 获取上传文件 token
  useEffect(() => {
    const getToken = () => {
      UploaderAPI.getToken().then((resp) => {
        const token = resp.data as IUploaderToken
        setUploaderToken(token.token)
      })
    }

    getToken()
    const intervalTimer = setInterval(getToken, 1000 * 60 * 15)
    return function cleanup() {
      clearInterval(intervalTimer)
    }
  }, [])

  return (
    <div id="whiteboard">
      {
        whiteBoardState.room !== undefined &&
        <React.Fragment>
          <RoomWhiteboard room={ whiteBoardState.room } className="whiteboard-main" />

          <div className="toolbar">
            <Menu>
              <Menu.Item key="selector">
                <Tooltip placement="right" title={ t("whiteboard_tool.selector") }>
                  <Button type="link" size="small" onClick={ () => setAppliance("selector") }
                    className={ memberState.currentApplianceName === "selector" ? "active" : "" }>
                    <MousePointerSVG className="icon" />
                  </Button>
                </Tooltip>
              </Menu.Item>

              <Menu.Item key="pencil">
                <Tooltip placement="right" title={ t("whiteboard_tool.pencil") }>
                  <Button type="link" size="small" onClick={ () => setAppliance("pencil") }
                    className={ memberState.currentApplianceName === "pencil" ? "active" : "" }>
                    <PencilAltSVG className="icon" />
                  </Button>
                </Tooltip>
              </Menu.Item>

              <Menu.Item key="text">
                <Tooltip placement="right" title={ t("whiteboard_tool.text") }>
                  <Button type="link" size="small" onClick={ () => setAppliance("text") }
                    className={ memberState.currentApplianceName === "text" ? "active" : "" }>
                    <TextSVG className="icon" />
                  </Button>
                </Tooltip>
              </Menu.Item>

              <Menu.Item key="rectangle">
                <Tooltip placement="right" title={ t("whiteboard_tool.rectangle") }>
                  <Button type="link" size="small" onClick={ () => setAppliance("rectangle") }
                    className={ memberState.currentApplianceName === "rectangle" ? "active" : "" }>
                    <SquareSVG className="icon" />
                  </Button>
                </Tooltip>
              </Menu.Item>

              <Menu.Item key="ellipse">
                <Tooltip placement="right" title={ t("whiteboard_tool.circle") }>
                  <Button type="link" size="small" onClick={ () => setAppliance("ellipse") }
                    className={ memberState.currentApplianceName === "ellipse" ? "active" : "" }>
                    <CircleSVG className="icon" />
                  </Button>
                </Tooltip>
              </Menu.Item>

              <Menu.Item key="stroke" id="whiteboard-stroke-settings">
                <Tooltip
                  placement="right"
                  title={ t("whiteboard_tool.stroke_settings") }
                  visible={ strokeTooltipState[0] }
                  onVisibleChange={ (visible) => setStrokeTooltipState([visible, false]) }>
                  <Popover
                    placement="right"
                    trigger="click"
                    visible={strokeTooltipState[1]}
                    onVisibleChange={ (visible) => setStrokeTooltipState([false, visible]) }
                    content={
                      <div id="whiteboard-stroke-settings">
                        <h6>{ t("whiteboard_tool.stroke_settings_color") }</h6>
                        <div className="option-colors">
                          {
                            colors.map((color) =>
                            <Button
                              key={color.name}
                              shape="circle"
                              className={ `${color.name}` }
                              style={{ backgroundColor: color.hex }}
                              onClick={ () => setStrokeColor(color.rgb) }
                            />)
                          }
                        </div>

                        <h6>{ t("whiteboard_tool.stroke_settings_thickness") }</h6>
                        <div className="option-width">
                          <svg width="100%" height="32" viewBox="0 0 269 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path
                              fill={`rgb(${memberState.strokeColor.join(",")})`}
                              stroke="#CCC"
                              fillRule="evenodd"
                              clipRule="evenodd"
                              d="M252 31.9693V32L0 16V15L252 0V0.030742C252.331 0.0103478 252.664 0 253 0C261.837 0 269 7.16344 269 16C269 24.8366 261.837 32 253 32C252.664 32 252.331 31.9897 252 31.9693Z" />
                          </svg>
                          <Slider
                            min={1}
                            max={32}
                            defaultValue={memberState.strokeWidth}
                            className="stroke-width-range"
                            onChange={(value) => setStrokeWidth(value as number)} />
                        </div>
                      </div>
                    }>

                    <Button type="link" size="small" id="whiteboard-stroke">
                      <span style={{ borderColor: `rgb(${memberState.strokeColor.join(",")})` }}>
                        <span style={{
                          backgroundColor: `rgb(${memberState.strokeColor.join(",")})`,
                          width: memberState.strokeWidth,
                          height: memberState.strokeWidth
                        }} />
                      </span>
                    </Button>
                  </Popover>
                </Tooltip>
              </Menu.Item>

              <Menu.Item key="eraser">
                <Tooltip placement="right" title={ t("whiteboard_tool.eraser") }>
                  <Button type="link" size="small" onClick={ () => setAppliance("eraser") }
                    className={ memberState.currentApplianceName === "eraser" ? "active" : "" }>
                    <EraserSVG className="icon" />
                  </Button>
                </Tooltip>
              </Menu.Item>

              <Menu.Item key="uploader">
                <Tooltip placement="right" title={ t("whiteboard_tool.insert_images") }>
                  <Upload
                    name="file"
                    action="https://up.qiniup.com"
                    accept="image/png,image/jpeg,image/gif"
                    showUploadList={false}
                    disabled={uploading}
                    data={{ token: uploaderToken }}
                    beforeUpload={uploaderBeforeUpload }
                    onChange={uploaderStatusOnChange}>
                    <Button type="link" size="small" disabled={uploading}>
                      { uploading ? <LoadingOutlined className="icon-uploading" /> : <ImagesSVG className="icon" /> }
                    </Button>
                  </Upload>
                </Tooltip>
              </Menu.Item>
            </Menu>
          </div>
        </React.Fragment>
      }
      {
        whiteBoardState.room === undefined &&
        <Spin className="whiteboard-loading" tip="Loading..." indicator={<ChalkboardSVG />} />
      }
    </div>
  )
}

// website/src/components/room/WhiteBoard.vue
<template>
  <div id="whiteboard">
    <div id="whiteboard-main"></div>

    <div class="toolbar">
      <ul class="nav">
        <li class="nav-item">
          <b-btn size="sm" variant="link" v-b-tooltip.hover.right title="Selector" @click="setAppliance('selector')" :class="{active: applianceName === 'selector'}">
            <Icon type="mouse-pointer" width="22" height="22" />
          </b-btn>
        </li>

        <li class="nav-item">
          <b-btn size="sm" variant="link" v-b-tooltip.hover.right title="Pencil" @click="setAppliance('pencil')" :class="{active: applianceName === 'pencil'}">
            <Icon type="pencil-alt" width="20" height="20" />
          </b-btn>
        </li>

        <li class="nav-item">
          <b-btn size="sm" variant="link" v-b-tooltip.hover.right title="Text" @click="setAppliance('text')" :class="{active: applianceName === 'text'}">
            <Icon type="text" width="20" height="20" />
          </b-btn>
        </li>

        <li class="nav-item">
          <b-btn size="sm" variant="link" v-b-tooltip.hover.right title="Rectangle" @click="setAppliance('rectangle')" :class="{active: applianceName === 'rectangle'}">
            <Icon type="square" width="22" height="22" />
          </b-btn>
        </li>

        <li class="nav-item">
          <b-btn size="sm" variant="link" v-b-tooltip.hover.right title="Circle" @click="setAppliance('ellipse')" :class="{active: applianceName === 'ellipse'}">
            <Icon type="circle" width="22" height="22" />
          </b-btn>
        </li>

        <li class="nav-item" id="whiteboard-stroke-settings">
          <b-btn size="sm" variant="link" id="whiteboard-stroke" title="Stroke settings" @click="$refs.colorTooltip.$emit('close')">
            <span :style="`border-color:${strokeColor.hex}`">
              <span :style="`background-color:${strokeColor.hex}; width:${strokeWidth}px; height:${strokeWidth}px;`"></span>
            </span>
          </b-btn>

          <b-tooltip ref="colorTooltip" target="whiteboard-stroke" placement="right">Stroke settings</b-tooltip>

          <b-popover target="whiteboard-stroke" container="whiteboard-stroke-settings" triggers="click blur">
            <h6>Color</h6>
            <div class="option-colors">
              <button
                v-for="(color, name) in predefineColors" :key="name"
                class="btn btn-sm"
                :class="[name, (strokeColor.hex === color.hex) && 'active']"
                :style="`background-color:${color.hex}`"
                @click="setStrokeColor(color)"></button>
            </div>

            <h6>Thickness</h6>
            <div class="option-width">
              <svg width="100%" height="32" viewBox="0 0 269 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path :fill="strokeColor.hex" stroke="#CCC" fill-rule="evenodd" clip-rule="evenodd" d="M252 31.9693V32L0 16V15L252 0V0.030742C252.331 0.0103478 252.664 0 253 0C261.837 0 269 7.16344 269 16C269 24.8366 261.837 32 253 32C252.664 32 252.331 31.9897 252 31.9693Z"></path>
              </svg>
              <input type="range" class="stroke-width-range" min="2" max="32" v-model.number="strokeWidth" />
            </div>
          </b-popover>
        </li>

        <li class="nav-item">
          <b-btn size="sm" variant="link" v-b-tooltip.hover.right title="Eraser" @click="setAppliance('eraser')" :class="{active: applianceName === 'eraser'}">
            <Icon type="eraser" width="22" height="22" />
          </b-btn>
        </li>

        <li class="nav-item">
          <el-upload
            class="image-uploader"
            action="https://up.qiniup.com"
            accept="image/png,image/jpeg,image/gif"
            multiple
            :data="uploadData"
            :show-file-list="false"
            :before-upload="beforeUpload"
            :on-progress="handleProgress"
            :on-success="handleSuccess">

            <b-btn size="sm" variant="link" v-b-tooltip.hover.right title="Insert Images">
              <Icon type="images" width="22" height="22" />
            </b-btn>
          </el-upload>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import uuid from 'uuid/v4'
import { mapState, mapGetters, mapActions } from 'vuex';
import { WhiteWebSdk } from 'white-web-sdk';
import { colors } from '@/utils/color'

import * as UploaderAPI from '@/api/uploader';

const whiteboardSdk = new WhiteWebSdk();

export default {

  data () {
    return {
      whiteboard: undefined,
      currentApplianceName: 'pencil',
      color: '#dc3545',
      predefineColors: colors,
      intervalTimer: 0,
    }
  },

  computed: {
    ...mapState("user", [
      "signedIn",
      "user"
    ]),

    ...mapState("uploader", [
      "token",
      "domain",
    ]),

    ...mapState("room", [
      "roomInfo",
      "RTC",
      "RTCUsers"
    ]),

    applianceName: {
      get: function () { return this.whiteboard && this.whiteboard.state.memberState.currentApplianceName },
      set: function (name) { this.whiteboard.setMemberState({ currentApplianceName: name }) }
    },

    strokeColor: {
      get: function () {
        if (this.whiteboard === undefined) return colors[0];

        for (const color of colors) {
          if (this.$lodash.isEqual(color.rgb, this.whiteboard.state.memberState.strokeColor)) return color
        }

        return colors[0]
      },
      set: function (color) {
        this.whiteboard.setMemberState({ strokeColor: color.rgb })
      }
    },

    strokeWidth: {
      get: function () { return this.whiteboard && this.whiteboard.state.memberState.strokeWidth },
      set: function (width) { this.whiteboard.setMemberState({ strokeWidth: width }) }
    },

    textSize: {
      get: function () { return this.whiteboard && this.whiteboard.state.memberState.textSize },
      set: function (size) { this.whiteboard.setMemberState({ textSize: size }) }
    },

    uploadData() {
      return {
        token: this.token
      }
    }
  },

  methods: {
    ...mapActions('uploader', [
      'getToken'
    ]),

    setAppliance(appliance) {
      this.whiteboard.setMemberState({ currentApplianceName: appliance })
      this.currentApplianceName = this.whiteboard.state.memberState.currentApplianceName
    },

    setStrokeColor(color) {
      this.strokeColor = color;
    },

    beforeUpload(file) {
      if (file.size > 1024 * 1024 * 2) {
        this.$message.error("Please upload pictures less than 2M.");
        return false
      }
    },

    handleProgress() {

    },

    handleSuccess(resp, file) {
      var _uuid = uuid()

      this.whiteboard.insertImage({
        uuid: _uuid,
        centerX: 0,
        centerY: 0,
        width: file.response.imageInfo.width,
        height: file.response.imageInfo.height,
      });

      UploaderAPI.getURL(file.response.key).then((resp) => {
        this.whiteboard.completeImageUpload(_uuid, resp.data.url);
      });
    },

    disconnect() {
      if (this.whiteboard.state.phase !== "disconnecting"){
        this.whiteboard.disconnect()
      }
    }
  },

  watch: {
    'RTC.roomState': function (state) {
      if (state !== 2) {
        this.disconnect();
      }
    }
  },

  created () {
    this.getToken();
    this.intervalTimer = setInterval(() => {
      this.getToken()
    }, 1000 * 60 * 15)

    window.addEventListener('resize', () => {
      if (this.whiteboard) this.whiteboard.refreshViewSize();
    });

    this.RTC.on("leaveRoom", () => {
      this.disconnect();
    })

    document.addEventListener('beforeunload', () => this.disconnect());
    window.addEventListener('beforeunload', () => this.disconnect());
  },

  mounted () {
    whiteboardSdk.joinRoom({ uuid: this.roomInfo.whiteboard_id, roomToken: this.roomInfo.whiteboard_token })
      .then((room) => {

        this.whiteboard = room
        this.whiteboard.setViewMode("broadcaster")
        this.whiteboard.setMemberState({
          currentApplianceName: 'pencil',
          strokeColor: this.strokeColor.rgb,
          strokeWidth: 4,
          textSize: 14
        })
        this.whiteboard.bindHtmlElement(document.getElementById('whiteboard-main'))
      })

  },

  destroyed() {
    clearInterval(this.intervalTimer)
    this.disconnect()
  }
}
</script>
